{% set version = "0.2.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bindrcpp
  version: {{ version|replace("-", "_") }}

source:
  fn: bindrcpp_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/bindrcpp_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bindrcpp/bindrcpp_{{ version }}.tar.gz
  sha256: 662dae785aee715855415f4e743281ccbf0832e426084dc2f0ca9c9c908ec9fa

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.16
    - r-bindr >=0.1.1
    - r-plogr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.16
    - r-bindr >=0.1.1
    - r-plogr

test:
  commands:
    - $R -e "library('bindrcpp')"           # [not win]
    - "\"%R%\" -e \"library('bindrcpp')\""  # [win]

about:
  home: https://github.com/krlmlr/bindrcpp, https://krlmlr.github.io/bindrcpp
  license: MIT
  summary: Provides an easy way to fill an environment with active bindings that call a C++ function.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'

extra:
  recipe-maintainers:
    - conda-forge/r
